<script>
export default {
  data() {
    return {
      // myJson: {
      //   class: "GraphLinksModel",
      //   copiesArrays: true,
      //   copiesArrayObjects: true,
      //   linkFromPortIdProperty: "fromPort",
      //   linkToPortIdProperty: "toPort",
      //   linkLabelKeysProperty: "labelKeys",
      //   nodeDataArray: [
      //     {
      //       key: 1,
      //       name: "\u53d8\u7535\u7ad91",
      //       loc: "-56 23",
      //       leftArray: [{ portId: "left0", portColor: "#01C0CA" }],
      //       topArray: [],
      //       bottomArray: [],
      //       rightArray: [],
      //     },
      //     {
      //       key: -2,
      //       name: "\u53d8\u7535\u7ad92",
      //       loc: "-289 22",
      //       leftArray: [],
      //       topArray: [],
      //       bottomArray: [],
      //       rightArray: [{ portId: "right0", portColor: "#01C0CA" }],
      //     },
      //     { category: "LinkLabel", key: -3 },
      //     {
      //       key: -4,
      //       name: "\u53d8\u7535\u7ad92",
      //       loc: "-175 -130",
      //       leftArray: [],
      //       topArray: [],
      //       bottomArray: [{ portId: "bottom0", portColor: "#01C0CA" }],
      //       rightArray: [],
      //     },
      //     { category: "LinkLabel", key: -5 },
      //   ],
      //   linkDataArray: [
      //     {
      //       from: -2,
      //       to: 1,
      //       labelKeys: [-3],
      //       fromPort: "right0",
      //       toPort: "left0",
      //     },
      //     {
      //       from: -4,
      //       to: -3,
      //       labelKeys: [-5],
      //       fromPort: "bottom0",
      //       toPort: "",
      //       category: "linkToLink"
      //     },
      //   ],
      // },

        myJson: {
          class: "GraphLinksModel",
          copiesArrays: true,
          copiesArrayObjects: true,
          linkFromPortIdProperty: "fromPort",
          linkToPortIdProperty: "toPort",
          linkLabelKeysProperty: "labelKeys",
          nodeDataArray: [
            {
              key: 2,
              name: "BDZ2",
              loc: "-200 734",
              background: "red",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#ddd", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
            { category: "LinkLabel", key: -6 },
            {
              key: -2,
              name: "BDZ2",
              loc: "-417 744",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#01C0CA", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
            {
              key: -3,
              name: "BDZ2",
              loc: "-199 528",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#01C0CA", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
            {
              key: -4,
              name: "BDZ2",
              loc: "-420 1045",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#01C0CA", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
            {
              key: -5,
              name: "BDZ2",
              loc: "-197 1036",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#01C0CA", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
            {
              key: -6,
              name: "BDZ2",
              loc: "-773 1054",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#01C0CA", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
            {
              key: -7,
              name: "BDZ2",
              loc: "-774 846",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#01C0CA", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
            {
              key: -8,
              name: "BDZ2",
              loc: "-773 545",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#01C0CA", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
            {
              key: -9,
              name: "BDZ2",
              loc: "-556 382",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#01C0CA", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
            {
              key: -10,
              name: "BDZ2",
              loc: "-203 372",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#01C0CA", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
            {
              key: -11,
              name: "BDZ2",
              loc: "147 519",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#01C0CA", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
            {
              key: -12,
              name: "BDZ2",
              loc: "146 724",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#01C0CA", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
            {
              key: -13,
              name: "BDZ2",
              loc: "143 1045",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#01C0CA", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
            {
              key: -14,
              name: "BDZ2",
              loc: "432 713",
              leftArray: [{ portColor: "#01C0CA ", portId: "left0" }],
              topArray: [{ portColor: "#01C0CA ", portId: "top0" }],
              bottomArray: [{ portColor: "#01C0CA  ", portId: "bottom0" }],
              rightArray: [
                { portColor: "#01C0CA", portId: "right0" },
                { portColor: "#01C0CA ", portId: "right1" },
              ],
            },
          ],
          linkDataArray: [
            {
              from: -2,
              labelKeys: [-6],
              to: 2,
              fromPort: "right0",
              toPort: "left0",
            },
            { from: -3, to: 2, fromPort: "bottom0", toPort: "top0" },
            { from: -4, to: -5, fromPort: "right0", toPort: "left0" },
            { from: -5, to: 2, fromPort: "right0", toPort: "right1" },
            { from: -6, to: -4, fromPort: "right0", toPort: "left0" },
            { from: -7, to: -6, fromPort: "bottom0", toPort: "left0" },
            { from: -8, to: -7, fromPort: "bottom0", toPort: "top0" },
            { from: -8, to: -9, fromPort: "top0", toPort: "left0" },
            { from: -10, to: -3, fromPort: "bottom0", toPort: "top0" },
            { from: -9, to: -10, fromPort: "right0", toPort: "left0" },
            { from: -3, to: -11, fromPort: "right0", toPort: "left0" },
            { from: -11, to: -12, fromPort: "bottom0", toPort: "top0" },
            {
              from: 2,
              to: -12,
              fromPort: "right0",
              toPort: "left0",
              ShapeColor: "#ddd",
            },
            { from: -5, to: -13, fromPort: "right1", toPort: "left0" },
            { from: -12, to: -13, fromPort: "bottom0", toPort: "top0" },
            { from: -12, to: -14, fromPort: "right0", toPort: "left0" },
            { from: -14, to: -13, fromPort: "bottom0", toPort: "right0" },
            { from: -14, to: -11, fromPort: "top0", toPort: "right0" },
            { from: -11, to: -10, fromPort: "top0", toPort: "right0" },
          ],
        },
    };
  },
};
</script>